INSERT INTO MDI_MAESTRO_COLUMNA (
        		DESCRIPCION,CODIGO,ID_MAESTRO_COLUMNA,DOMINIO,FECHA_ACTUALIZACION,
        		FECHA_CREACION,USUARIO_CREACION,USUARIO_ACTUALIZACION,TERMINAL_ACTUALIZACION,TERMINAL_CREACION,
        		APLICACION,ESTADO)
        		VALUES('CARTA DE VISITA',169,MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL,'TIPO_DOC_ADJUNTO',NULL,
        		SYSDATE,'SYSTEM',NULL,NULL,'LOCALHOST',
        		'INPS','1');