CREATE TABLE "NPS_INTEGRADO"."PGH_COMENTARIO_DETSUP_OPC" 
   (	
	"ID_COMENTARIO_DETSUP_OPC" NUMBER(10,0) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(100 BYTE), 
	"FECHA_CREACION" DATE NOT NULL ENABLE, 
	"TERMINAL_CREACION" VARCHAR2(38 BYTE) NOT NULL ENABLE, 
	"FECHA_ACTUALIZACION" DATE, 
	"USUARIO_ACTUALIZACION" VARCHAR2(38 BYTE), 
	"TERMINAL_ACTUALIZACION" VARCHAR2(38 BYTE), 
	"USUARIO_CREACION" VARCHAR2(38 BYTE) NOT NULL ENABLE, 
	"ID_DETALLE_SUPERVISION" NUMBER(10,0), 
	"ID_ESCENARIO_INCUMPLIDO" NUMBER(10,0), 
	"ESTADO" VARCHAR2(1 BYTE), 
	 CONSTRAINT "PGH_COMENTARIO_DETSUP_OPC_PK" PRIMARY KEY ("ID_COMENTARIO_DETSUP_OPC")
		  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
		  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
		  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
		  TABLESPACE "TS_MEDIUM_D"  ENABLE, 
	 CONSTRAINT "PGH_DETSUP_DETSUP_OPC_FK" FOREIGN KEY ("ID_DETALLE_SUPERVISION")
		REFERENCES "NPS_INTEGRADO"."PGH_DETALLE_SUPERVISION" ("ID_DETALLE_SUPERVISION") ENABLE, 
	 CONSTRAINT "PGH_ESC_INC_DETSUP_OPC_FK" FOREIGN KEY ("ID_ESCENARIO_INCUMPLIDO")
		REFERENCES "NPS_INTEGRADO"."PGH_ESCENARIO_INCUMPLIDO" ("ID_ESCENARIO_INCUMPLIDO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MEDIUM_D" ;
  
   COMMENT ON COLUMN "NPS_INTEGRADO"."PGH_COMENTARIO_DETSUP_OPC"."ID_COMENTARIO_DETSUP_OPC" IS 'Identificador principal de la tabla PGH_COMENTARIO_DETSUP_OPC';
   
   COMMENT ON COLUMN "NPS_INTEGRADO"."PGH_COMENTARIO_DETSUP_OPC"."DESCRIPCION" IS 'Descripcion del comentario opcional';
   
   COMMENT ON COLUMN "NPS_INTEGRADO"."PGH_COMENTARIO_DETSUP_OPC"."FECHA_CREACION" IS 'Fecha de Creacion del registro';
   
   COMMENT ON COLUMN "NPS_INTEGRADO"."PGH_COMENTARIO_DETSUP_OPC"."TERMINAL_CREACION" IS 'terminal de donde se creo el registro';
   
   COMMENT ON COLUMN "NPS_INTEGRADO"."PGH_COMENTARIO_DETSUP_OPC"."FECHA_ACTUALIZACION" IS 'Fecha de Actualizacion del registro';
   
   COMMENT ON COLUMN "NPS_INTEGRADO"."PGH_COMENTARIO_DETSUP_OPC"."USUARIO_ACTUALIZACION" IS 'Usuario que modifico el registro';
   
   COMMENT ON COLUMN "NPS_INTEGRADO"."PGH_COMENTARIO_DETSUP_OPC"."TERMINAL_ACTUALIZACION" IS 'Terminal de donde se modifico el registro';
   
   COMMENT ON COLUMN "NPS_INTEGRADO"."PGH_COMENTARIO_DETSUP_OPC"."USUARIO_CREACION" IS 'Usuario quien realizo el registro';
   
   COMMENT ON COLUMN "NPS_INTEGRADO"."PGH_COMENTARIO_DETSUP_OPC"."ID_DETALLE_SUPERVISION" IS 'Identificador de la tabla PGH_DETALLE_SUPERVISION';
   
   COMMENT ON COLUMN "NPS_INTEGRADO"."PGH_COMENTARIO_DETSUP_OPC"."ID_ESCENARIO_INCUMPLIDO" IS 'Identificador  de la tabla PGH_ESCENARIO_INCUMPLIDO';
   
   COMMENT ON COLUMN "NPS_INTEGRADO"."PGH_COMENTARIO_DETSUP_OPC"."ESTADO" IS 'Estado del registro 1: Activo 0: Inactivo';
  
  CREATE SEQUENCE  "NPS_INTEGRADO"."PGH_COMENTARIO_DETSUP_OPC_SEQ"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE ;